import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    map: {
        width: "100%",
        height: "100%",
    },
    routeSearchContainer: {
        position: "absolute",
        top: 5,
        left: 10,
        right: 10,
    },
    background: {
        position: "absolute",
        left: 0,
        right: 0,
        top: 0,
        height: 300,
    },
    headerContainer: {
        position: "absolute",
        top: 40,
        width: "100%",
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 10,
        gap: 10,
    },
    containerContent: {
        backgroundColor: "#FFFFFF79",
        boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
        borderRadius: 20,
        padding: 0,
        margin: 0,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
    },
    inputContainerSearch: {
        top: 0,
        flex: 1,
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
    },
    inconClear: {
        right: "5%",
        position: "absolute",
        boxShadow: "0 0 10px #FFFFFF",
        borderRadius: 50,
        backgroundColor: "#E4E4E43D",
        filter: "drop-shadow(0 0 2px #000000)",
    },
    blurContainer: {
        flex: 1,
        backgroundColor: "#FFFFFF44",
    },
    icon: {
        marginLeft: 20,
    },
    label: {
        fontSize: 14,
        fontWeight: "600",
        marginBottom: 5,
        color: "#333",
    },
    input: {
        margin: 10,
        flex: 1,
        fontWeight: "600",
        color: "#000000",
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 8,
        padding: 10,
        fontSize: 15,
        backgroundColor: "#f9f9f9",
    },
    routeSearchContainerCP: {
        top: 20,
        left: 20,
        right: 20,
        backgroundColor: "white",
        borderRadius: 12,
        padding: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        maxHeight: "80%",
        maxWidth: "90%",
    },
    searchHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 15,
    },
    searchTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#5C0DB6",
    },
    closeButton: {
        fontSize: 24,
        color: "#999",
    },
    inputContainer: {
        marginBottom: 15,
    },
    suggestionsContainer: {
        position: "absolute",
        top: 65,
        left: 60,
        right: 80,
        maxHeight: 150,
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 8,
        marginTop: 5,
        backgroundColor: "#FFFFFF",
    },
    suggestionItem: {
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
    },
    suggestionText: {
        fontSize: 14,
        color: "#333",
    },
    actionButtons: {
        flexDirection: "row",
        gap: 10,
        marginTop: 10,
    },
    routeButton: {
        flex: 1,
        padding: 12,
        borderRadius: 8,
        alignItems: "center",
    },
    calculateButton: {
        backgroundColor: "#5C0DB6",
    },
    clearButton: {
        backgroundColor: "#FF6347",
    },
    buttonText: {
        color: "white",
        fontWeight: "600",
        fontSize: 14,
    },
    routeInfo: {
        marginTop: 15,
        padding: 12,
        backgroundColor: "#f0f0f0",
        borderRadius: 8,
    },
    routeInfoText: {
        fontSize: 14,
        color: "#333",
        marginBottom: 5,
    },
    errorText: {
        marginTop: 6,
        color: "#B00020",
        fontSize: 12,
    },
    toolsContainer: {
        backgroundColor: "#FFFFFF",
        position: "absolute",
        display: "flex",
        width: "100%",
        flexDirection: "row",
        bottom: 10,
        left: 10,
        right: 10,
        height: 50,
    },
    toolsContainerLeft: {
        position: "absolute",
        bottom: 10,
        left: 20,
        width: "20%",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        backgroundColor: "#D60E0E",
    },
    toolsContainerRight: {
        gap: 10,
        position: "absolute",
        bottom: 10,
        right: 10,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        backgroundColor: "#096DCA",
    },
});
